name: Configuration split
type: module
description: Configuration filter for importing and exporting split config
# core: 8.x
package: Other
dependencies:
  - config

# Information added by Drupal.org packaging script on 2016-09-25
version: '8.x-1.x-dev'
core: '8.x'
project: 'config_split'
datestamp: 1474844941
